<header class="header">
    <nav class="nav">
        <div class="logo">
            </div>

        <ul id="menu">
            {{- range site.Menus.main }}
            {{- $menu_item_url := .URL | absLangURL }}
            {{- $page_url := .Page.Permalink | absLangURL }}
            <li>
                <a href="{{ .URL | absLangURL }}" title="{{ .Name }}">
                    <span {{ if eq $menu_item_url $page_url }}class="active"{{ end }}>
                        {{ .Name }}
                    </span>
                    {{- if findRE "://" .URL }}
                    &nbsp;
                    <svg fill="none" shape-rendering="geometricPrecision" stroke="currentColor" stroke-linecap="round"
                         stroke-linejoin="round" stroke-width="2.5" viewBox="0 0 24 24" height="12" width="12">
                        <path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6"></path>
                        <path d="M15 3h6v6"></path>
                        <path d="M10 14L21 3"></path>
                    </svg>
                    {{- end }}
                </a>
            </li>
            {{- end }}
        </ul>
    </nav>
</header>
