# 這是您網站唯一的、修正過的設定檔
baseURL = "https://nda.pages.dev/"
languageCode = "zh-TW"
title = "風向 Pulse"
theme = "PaperMod"

# Hugo 的分頁設定 (已修正為新版語法)
[pagination]
  pagerSize = 10

# PaperMod 主題的參數設定
[params]
  author = "風向 Pulse"
  description = "以事實、常識、邏輯，觀世界"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

  # 首頁的個人簡介模式 (Profile Mode)
  [params.profileMode]
    enabled = true
    title = "風向 Pulse"
    subtitle = "以事實、常識、邏輯，觀世界"
    imageUrl = "/img/logo.svg" # 確保您的 Logo 路徑是 static/img/logo.svg
    imageWidth = 240
    imageHeight = 120

    [[params.profileMode.buttons]]
      name = "瀏覽所有文章"
      url = "/posts"

# 網站頂部的導覽列選單
[[menu.main]]
  identifier = "archives"
  name = "文章封存"
  url = "/archives/"
  weight = 10

[[menu.main]]
  identifier = "search"
  name = "搜尋"
  url = "/search/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "標籤"
  url = "/tags/"
  weight = 30
