baseURL = "https://nda.pages.dev/"
languageCode = "zh-cn"
title = "風向 Pulse"
theme = "paperMod"
timeZone = "Asia/Shanghai"

[menu]
  [[menu.main]]
    name = "首頁"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "每日新聞"
    url = "/posts/"
    weight = 10
