baseURL = 'https://nda.pages.dev/'
title = '風向 Pulse 3'
theme = "PaperMod"
languageCode = "zh-cn"
hasCJKLanguage = true
defaultContentLanguage = "zh"

[params]
  env = "production" # 可選：development / production

  [params.profileMode]
    enabled = true
    title = "風向 Pulse 3"
    subtitle = "以事實、常識、邏輯，觀世界"
    imageUrl = "img/logo.png"
    imageWidth = 120
    imageHeight = 120



