baseURL = "https://nda.pages.dev/"
languageCode = "zh-TW"
title = "風向 Pulse"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "風向 Pulse"
  description = "以事實、常識、邏輯，觀世界"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  logo = "/img/logo.svg"   # 這行設定 logo，小寫 logo

[[menu.main]]
  identifier = "archives"
  name = "文章封存"
  url = "/archives/"
  weight = 10

[[menu.main]]
  identifier = "search"
  name = "站內搜尋"
  url = "/search/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "所有標籤"
  url = "/tags/"
  weight = 30
